version: '2.2'
services:
  elasticsearch01:
    build: ./es
    container_name: elasticsearch01
    environment:
      - node.name=elasticsearch01
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=eselasticsearch01,eselasticsearch02,eselasticsearch03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 
        soft: 65536
        hard: 65536
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9201:9200
    networks:
      - esnet

  elasticsearch02:
    build: ./es
    container_name: elasticsearch02
    environment:
      - node.name=elasticsearch02
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=eselasticsearch01,eselasticsearch02,eselasticsearch03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 
        soft: 65536
        hard: 65536
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9202:9200
    networks:
      - esnet

  elasticsearch03:
    build: ./es
    container_name: elasticsearch03
    environment:
      - node.name=elasticsearch03
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=eselasticsearch01,eselasticsearch02,eselasticsearch03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 
        soft: 65536
        hard: 65536
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9203:9200
    networks:
      - esnet

  kibana:
    build: ./kibana
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    volumes:
      - kibanadata:/usr/share/kibana/data

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibanadata:
    driver: local
  

networks:
  esnet: